use_frameworks!

target 'JRNetwork_Example' do
  pod 'JRNetwork', :path => '../'
  pod 'Alamofire'
  #pod 'ObjectMapper'
  pod 'PromiseKit/CorePromise'

  target 'JRNetwork_Tests' do
    inherit! :search_paths

    
  end
end


